apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: santa-deployment
spec:
  selector:
    matchLabels:
      app: santa
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: santa
    spec:
      containers:
        - name: santa
          image: prashantritgit/santa222:latest # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
